# Generated by Django 4.1.3 on 2022-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartposition',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
