# Generated by Django 4.1.3 on 2022-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('cart', '0003_cartposition_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='orders',
            field=models.ManyToManyField(to='orders.order'),
        ),
    ]
