# Generated by Django 4.1.3 on 2022-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartposition_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='status',
            field=models.CharField(default='cart', max_length=50),
        ),
    ]
