# Generated by Django 4.1.3 on 2022-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartposition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
