# Generated by Django 4.1.3 on 2022-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartposition_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
