# Generated by Django 4.1.3 on 2022-11-30 14:55

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cartposition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartposition',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[cart.models.ValidatePrice]),
        ),
    ]
