# Generated by Django 4.1.3 on 2022-11-25 10:58

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[orders.models.ValidatePrice]),
        ),
    ]
